# EXOCORTEX_SQUAD_ARENA.py
import pygame
import torch
import torch.nn.functional as F
import math
import numpy as np
import time
import random
import sys

# Ensure global compatibility: all internal logic, comments, and variables are strictly in English.
# TACTICAL SPLIT: 6 Classes mapped onto 6 distinct non-linear spectral frequencies.
# WEAPON SOLITONS: Independent, physics-grounded self-propulsion and waveguides for Bow, Shuriken & Magic.

WIDTH, HEIGHT = 1200, 800  
ARENA_WIDTH = 800
COMPUTE_RES = 128
TOURNAMENT_SEED = 202607
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# =====================================================================
# GLOBAL COMBAT BALANCE & MATCHUP PREDICTION CONFIGURATION
# =====================================================================

COMBAT_BALANCE_CONFIG = {
    # --- MATCH RULES & TIMEOUT ---
    "MATCH_DURATION_LIMIT": 90.0,   # Standard 90-second time limit per match.
    "ATTACKER_TIMEOUT_PENALTY": True, # If 90s expires, Attacker (Team 0) automatically LOSES (Defeat).

    # --- BASE POWER FORMULA CONSTANTS ---
    "BASE_POWER_START": 1000,
    "BASE_POWER_PER_LEVEL": 150,

    # --- STANDARDIZED CONSTANT HEALING & DAMAGE (DPS > HPS) ---
    # Constant HP restoration factor when absorbing 6Hz Theta mist
    "BASE_HEAL_RATE": 0.025,
    # Theta mist density generated per second by channel_heal
    "HEAL_MIST_CHANNEL_POWER": 10.0,
    # Theta mist density generated by ranged heal soliton
    "HEAL_SOLITON_POWER": 1.0,

    # --- DAMAGE & SHIELD PHYSICS ---
    # Base constant factor for Gamma spectral damage (Focused DPS cleanly out-damages HPS)
    "DAMAGE_SCALE_BASE": 0.085,
    # Percentage of damage passing through an active 10Hz Alpha shield field
    "SHIELD_PENETRATION_RATIO": 0.20,
    # Density of 10Hz Alpha shield generated by Shield channel
    "SHIELD_CHANNEL_POWER": 35.0,

    # --- PREDICTIVE MATCHUP ENGINE COEFFICIENTS ---
    "PREDICTION_SIGMOID_SCALE": 0.12, # Scale factor for win probability relative to TTK difference
}

WEAPON_CONFIGS = {
    "Sword": {
        "power_mult": 1.15,
        "dps_weight": 1.20,
        "hps_weight": 0.00,
        "range": 30.0,
        "cooldown": 0.8,
        "type": "melee",
        "desc": "High close-range slicing DPS and Beta kinetic momentum."
    },
    "Bow": {
        "power_mult": 1.20,
        "dps_weight": 1.15,
        "hps_weight": 0.00,
        "range": 350.0,
        "cooldown": 1.2,
        "type": "ranged",
        "desc": "Long-range aerodynamic arrow solitons."
    },
    "Shuriken": {
        "power_mult": 1.25,
        "dps_weight": 1.25,
        "hps_weight": 0.00,
        "range": 220.0,
        "cooldown": 0.9,
        "type": "ranged",
        "desc": "Triple spread backdodging solitons."
    },
    "Magic": {
        "power_mult": 1.30,
        "dps_weight": 1.35,
        "hps_weight": 0.00,
        "range": 280.0,
        "cooldown": 2.0,
        "type": "channeled",
        "desc": "High-frequency Gamma beam burst."
    },
    "Shield": {
        "power_mult": 0.95,
        "dps_weight": 0.20,
        "hps_weight": 0.00,
        "range": 40.0,
        "cooldown": 2.0,
        "type": "defensive",
        "desc": "Generates 10Hz Alpha protective barrier field."
    },
    "Heal": {
        "power_mult": 1.10,
        "dps_weight": 0.00,
        "hps_weight": 0.80,
        "range": 250.0,
        "cooldown": 1.5,
        "type": "support",
        "desc": "Injects 6Hz Theta restorative mist."
    }
}

CREATURE_CONFIGS = {
    "Dendro": {
        "power_mult": 1.00,
        "speed_mult": 1.00,
        "hp_mult": 1.10,
        "desc": "Nature affinity, robust frame (+10% HP)."
    },
    "Necro": {
        "power_mult": 1.05,
        "speed_mult": 0.95,
        "hp_mult": 0.95,
        "desc": "Spectral decay, slightly higher combat weight."
    },
    "Demon": {
        "power_mult": 1.15,
        "speed_mult": 0.80,
        "hp_mult": 1.25,
        "desc": "Demonic plate armor (-20% Speed, +25% HP)."
    },
    "Furry": {
        "power_mult": 1.00,
        "speed_mult": 1.40,
        "hp_mult": 0.85,
        "desc": "High agility (+40% Speed, -15% HP)."
    },
    "Human": {
        "power_mult": 1.00,
        "speed_mult": 1.00,
        "hp_mult": 1.00,
        "desc": "Standard baseline physical attributes."
    },
    "Angel": {
        "power_mult": 1.10,
        "speed_mult": 1.10,
        "hp_mult": 1.05,
        "desc": "Holy essence (+10% Speed, +5% HP)."
    }
}

def predict_squad_matchup(team0_actors, team1_actors):
    """
    Closed-form O(N) deterministic matchup prediction engine:
    Calculates Effective DPS, HPS, EHP, Time-To-Kill (TTK) and Attacker Win Probability
    taking the 90-second timeout rule strictly into account.
    """
    def calc_squad_stats(actors):
        edps = 0.0
        ehps = 0.0
        ehp = 0.0
        for a in actors:
            if getattr(a, 'is_dead', False): continue
            w_cfg = WEAPON_CONFIGS.get(a.weapon, {"dps_weight": 1.0, "hps_weight": 0.0})
            c_cfg = CREATURE_CONFIGS.get(a.creature, {"hp_mult": 1.0, "power_mult": 1.0})
            
            lvl_scale = (1.0 + a.level * 0.1) * (0.5 + a.quality / 100.0)
            
            unit_dps = w_cfg["dps_weight"] * COMBAT_BALANCE_CONFIG["DAMAGE_SCALE_BASE"] * 100.0 * c_cfg["power_mult"] * lvl_scale
            unit_hps = w_cfg["hps_weight"] * COMBAT_BALANCE_CONFIG["BASE_HEAL_RATE"] * 100.0 * c_cfg["power_mult"] * lvl_scale
            unit_hp = getattr(a, 'integrity', 1.0) * 100.0 * c_cfg["hp_mult"]
            
            edps += unit_dps
            ehps += unit_hps
            ehp += unit_hp
            
        return edps, ehps, ehp

    edps0, ehps0, ehp0 = calc_squad_stats(team0_actors)
    edps1, ehps1, ehp1 = calc_squad_stats(team1_actors)

    # Net damage output considering opposing healing
    net_dps0_to_1 = max(0.1, edps0 - ehps1 * 0.5)
    net_dps1_to_0 = max(0.1, edps1 - ehps0 * 0.5)

    ttk0_to_1 = ehp1 / net_dps0_to_1  # Seconds required for Team 0 to wipe Team 1
    ttk1_to_0 = ehp0 / net_dps1_to_0  # Seconds required for Team 1 to wipe Team 0

    match_limit = COMBAT_BALANCE_CONFIG["MATCH_DURATION_LIMIT"]

    # Attacker (Team 0) MUST destroy Defender (Team 1) before 90-second match limit
    if ttk0_to_1 > match_limit:
        win_prob_0 = max(0.0, 1.0 - (ttk0_to_1 - match_limit) / 30.0) * 0.15
    else:
        ttk_diff = ttk1_to_0 - ttk0_to_1
        scale = COMBAT_BALANCE_CONFIG["PREDICTION_SIGMOID_SCALE"]
        win_prob_0 = 1.0 / (1.0 + math.exp(-scale * ttk_diff))

    return {
        "team0_edps": edps0, "team0_ehps": ehps0, "team0_ehp": ehp0, "ttk_0_to_1": ttk0_to_1,
        "team1_edps": edps1, "team1_ehps": ehps1, "team1_ehp": ehp1, "ttk_1_to_0": ttk1_to_0,
        "win_probability_0": win_prob_0 * 100.0
    }

class StandaloneFluidSolver:
    def __init__(self, res, device):
        self.res = res
        self.device = device
        y, x = torch.meshgrid(
            torch.linspace(-1.0, 1.0, res, device=device),
            torch.linspace(-1.0, 1.0, res, device=device), indexing='ij'
        )
        self.grid_x = x
        self.grid_y = y

    def advect(self, field, u, v, dt):
        dx = u[0, 0] * (dt * 2.0 / self.res)
        dy = v[0, 0] * (dt * 2.0 / self.res)
        sampling_grid = torch.stack([self.grid_x - dx, self.grid_y - dy], dim=-1).unsqueeze(0)
        sampling_grid = torch.clamp(sampling_grid, -1.0, 1.0)
        return F.grid_sample(field, sampling_grid, mode='bilinear', padding_mode='zeros', align_corners=True)

    def compute_laplacian(self, field):
        """ Isotropic 9-point Laplacian stencil (Patra-Cartwright formulation) for O(dx^4) rotational invariance """
        field_pad = F.pad(field, (1, 1, 1, 1), mode='replicate')
        
        center = field
        c_sum = (field_pad[:, :, 1:-1, 2:] + field_pad[:, :, 1:-1, :-2] +
                 field_pad[:, :, 2:, 1:-1] + field_pad[:, :, :-2, 1:-1])
        
        d_sum = (field_pad[:, :, 2:, 2:] + field_pad[:, :, 2:, :-2] +
                 field_pad[:, :, :-2, 2:] + field_pad[:, :, :-2, :-2])
        
        return (4.0 * c_sum + 1.0 * d_sum - 20.0 * center) / 6.0

    def compute_gradient(self, field):
        """ Isotropic 9-point Scharr gradient operator for rotationally symmetric derivative field calculation """
        field_pad = F.pad(field, (1, 1, 1, 1), mode='replicate')
        t_left, t_mid, t_right = field_pad[:, :, :-2, :-2], field_pad[:, :, :-2, 1:-1], field_pad[:, :, :-2, 2:]
        m_left,        m_right = field_pad[:, :, 1:-1, :-2],                            field_pad[:, :, 1:-1, 2:]
        b_left, b_mid, b_right = field_pad[:, :, 2:, :-2],  field_pad[:, :, 2:, 1:-1],  field_pad[:, :, 2:, 2:]
        
        gx = (3.0 * (t_right - t_left) + 10.0 * (m_right - m_left) + 3.0 * (b_right - b_left)) / 32.0
        gy = (3.0 * (b_left - t_left) + 10.0 * (b_mid - t_mid) + 3.0 * (b_right - t_right)) / 32.0
        return gx, gy

    def project(self, u, v, wall_density):
        block_mask = (wall_density > 0.4).float()
        u = u * (1.0 - block_mask)
        v = v * (1.0 - block_mask)
        
        du_dx, _ = self.compute_gradient(u)
        _, dv_dy = self.compute_gradient(v)
        div = du_dx + dv_dy
        
        p = torch.zeros_like(u)
        for _ in range(10):
            p_pad = F.pad(p, (1, 1, 1, 1), mode='replicate')
            c_sum = (p_pad[:, :, 1:-1, 2:] + p_pad[:, :, 1:-1, :-2] + 
                     p_pad[:, :, 2:, 1:-1] + p_pad[:, :, :-2, 1:-1])
            d_sum = (p_pad[:, :, 2:, 2:] + p_pad[:, :, 2:, :-2] + 
                     p_pad[:, :, :-2, 2:] + p_pad[:, :, :-2, :-2])
            p = (4.0 * c_sum + 1.0 * d_sum - 6.0 * div) / 20.0
                    
        dp_dx, dp_dy = self.compute_gradient(p)
        u -= dp_dx
        v -= dp_dy
        
        return u * (1.0 - block_mask), v * (1.0 - block_mask)

class SoftbodyActor:
    def __init__(self, spawn_pos, team, color, name, style, weapon, creature, level, quality):
        self.pos = torch.tensor(spawn_pos, dtype=torch.float32, device=device)
        self.team = team
        self.color = color
        self.name = name
        self.style = style  
        self.weapon = weapon  
        self.creature = creature  
        self.level = level
        self.quality = quality
        
        self.integrity = 1.0
        self.ult_charge = 0.0
        self.is_dead = False
        self.current_action = "[IDLE]" 
        
        self.breather_phase = random.uniform(0.0, 2.0 * math.pi)
        self.breather_speed = 3.5 if style == "Fighter" else 1.8
        
        self.pin_x = torch.tensor([10.14, 7.43, 2.75, 2.72, -2.72, -2.75, -7.42, -10.14, -10.14, -7.43, -2.75, -2.72, 2.72, 2.75, 7.43, 10.14], device=device) * 1.5
        self.pin_y = torch.tensor([-2.72, -7.43, -4.77, -10.15, -10.14, -4.77, -7.42, -2.73, 2.72, 7.43, 4.76, 10.14, 10.15, 4.77, 7.42, 2.71], device=device) * 1.5
        
        self.pin_pos = torch.zeros((16, 2), dtype=torch.float32, device=device)
        self.pin_pos[:, 0] = self.pos[0] + self.pin_x
        self.pin_pos[:, 1] = self.pos[1] + self.pin_y
        self.edge_intact = torch.ones(16, dtype=torch.bool, device=device)
        self.node_phases = torch.zeros(16, dtype=torch.float32, device=device)
        self.angle = 0.0
        
        self.idx_I = torch.arange(16, device=device)
        self.idx_J = torch.remainder(self.idx_I + 1, 16)
        
        w_cfg = WEAPON_CONFIGS.get(self.weapon, {"cooldown": 1.0})
        self.cooldown = random.uniform(0.1, w_cfg["cooldown"])
        self.channel_duration = 0.0
        self.channel_target = None
        self.power = self.calculate_power()

    def calculate_power(self):
        """ Closed-form O(1) linear power rating formula derived strictly from balance constants """
        base = COMBAT_BALANCE_CONFIG["BASE_POWER_START"] + self.level * COMBAT_BALANCE_CONFIG["BASE_POWER_PER_LEVEL"]
        qual_mult = 0.5 + (self.quality / 100.0)
        
        w_cfg = WEAPON_CONFIGS.get(self.weapon, {"power_mult": 1.0, "dps_weight": 1.0, "hps_weight": 0.0})
        c_cfg = CREATURE_CONFIGS.get(self.creature, {"power_mult": 1.0, "hp_mult": 1.0, "speed_mult": 1.0})
        
        effective_output = w_cfg.get("dps_weight", 0.0) + w_cfg.get("hps_weight", 0.0)
        weapon_impact = w_cfg["power_mult"] * (0.7 + 0.3 * effective_output)
        creature_impact = c_cfg["power_mult"] * (0.5 * c_cfg["hp_mult"] + 0.5 * c_cfg["speed_mult"])
        
        total_power = int(base * qual_mult * weapon_impact * creature_impact)
        return total_power

    def calculate_covariance(self):
        com = self.pin_pos.mean(dim=0)
        dx_local = self.pin_pos[:, 0] - com[0]
        dy_local = self.pin_pos[:, 1] - com[1]
        cross_cov = torch.sum(self.pin_y * dx_local - self.pin_x * dy_local)
        dot_cov = torch.sum(self.pin_x * dx_local + self.pin_y * dy_local) + 1e-5
        raw_angle = torch.atan2(cross_cov, dot_cov).item()
        
        angle_diff = (raw_angle - self.angle + math.pi) % (2 * math.pi) - math.pi
        self.angle += angle_diff * 0.40
        return com

    def update_springs(self, ideal_pos):
        d_curr = torch.norm(self.pin_pos[self.idx_I] - self.pin_pos[self.idx_J], dim=1)
        d_rest = torch.norm(ideal_pos[self.idx_I] - ideal_pos[self.idx_J], dim=1)
        strain = d_curr / (d_rest + 1e-5)
        
        self.edge_intact = self.edge_intact & ~(strain > 2.8 + self.integrity * 2.5)
        self.edge_intact = self.edge_intact | (strain < 1.05)
        
        dir_mutual = (self.pin_pos[self.idx_J] - self.pin_pos[self.idx_I]) / (d_curr.unsqueeze(1) + 1e-5)
        f_mag = 200.0 * (self.integrity + 0.15) * (d_curr - d_rest)
        
        f_mutual_I = dir_mutual * f_mag.unsqueeze(1) * self.edge_intact.float().unsqueeze(1)
        f_mutual_prev = torch.roll(f_mutual_I, shifts=1, dims=0)
        return torch.clamp(f_mutual_I - f_mutual_prev, -300.0, 350.0)

def apply_cohesion_constraint(pin_pos, ideal_pos, scale, cohesion_level):
    max_allowed = scale * (20.0 - cohesion_level * 15.0) if cohesion_level < 0.0 else scale * (5.0 + (1.0 - cohesion_level) * 15.0)
    diff = pin_pos - ideal_pos
    dist = torch.norm(diff, dim=1, keepdim=True) + 1e-5
    over_limit = dist > max_allowed
    if over_limit.any():
        return torch.where(over_limit, ideal_pos + (diff / dist) * max_allowed, pin_pos)
    return pin_pos

class TacticalBus:
    """ Asynchronous per-frame Event Broker for squad coordination """
    def __init__(self):
        self.clear()

    def clear(self):
        self.attack_corridors = {0: [], 1: []}
        self.heal_requests = {0: [], 1: []}
        self.defense_requests = {0: [], 1: []}

    def publish_corridor(self, team, attacker_name, source, target, weapon):
        self.attack_corridors[team].append({
            "source": np.array(source, dtype=np.float32),
            "target": np.array(target, dtype=np.float32),
            "attacker": attacker_name,
            "weapon": weapon
        })

    def publish_heal_request(self, team, requester_name, pos, integrity):
        urgency = 1.0 - integrity
        if urgency > 0.05:
            self.heal_requests[team].append({
                "requester": requester_name,
                "pos": np.array(pos, dtype=np.float32),
                "urgency": urgency
            })

    def publish_defense_request(self, team, requester_name, pos, threat_source, urgency):
        if urgency > 0.1:
            self.defense_requests[team].append({
                "requester": requester_name,
                "pos": np.array(pos, dtype=np.float32),
                "threat_source": np.array(threat_source, dtype=np.float32),
                "urgency": urgency
            })

def compute_corridor_avoidance(actor_pos, friendly_corridors, clearance=60.0):
    avoid_steer = np.array([0.0, 0.0])
    p = actor_pos.cpu().numpy() if torch.is_tensor(actor_pos) else np.array(actor_pos)
    
    for corr in friendly_corridors:
        a = corr["source"]
        b = corr["target"]
        
        ab = b - a
        ab_len = math.hypot(ab[0], ab[1]) + 1e-5
        ab_unit = ab / ab_len
        
        ap = p - a
        proj = np.dot(ap, ab_unit)
        
        if -10.0 < proj < ab_len + 20.0:
            closest = a + ab_unit * proj
            perp_vec = p - closest
            dist_perp = math.hypot(perp_vec[0], perp_vec[1]) + 1e-5
            
            if dist_perp < clearance:
                if dist_perp < 1e-3:
                    normal = np.array([-ab_unit[1], ab_unit[0]])
                else:
                    normal = perp_vec / dist_perp
                    
                push_factor = (clearance - dist_perp) / clearance
                avoid_steer += normal * push_factor * 2.0
                
    return avoid_steer

class BossFightArena:
    def __init__(self, master_seed=TOURNAMENT_SEED, current_stage=1, ally_level=20, alch_resources=0.0):
        self.master_seed = master_seed
        self.current_stage = current_stage
        self.ally_level = ally_level
        self.alch_resources = alch_resources
        
        self.solver = StandaloneFluidSolver(COMPUTE_RES, device)
        self.bus = TacticalBus()
        self.u = torch.zeros((1, 1, COMPUTE_RES, COMPUTE_RES), device=device)
        self.v = torch.zeros((1, 1, COMPUTE_RES, COMPUTE_RES), device=device)
        self.density_spectral = torch.zeros((1, 100, COMPUTE_RES, COMPUTE_RES), device=device)
        
        y, x = self.solver.grid_y, self.solver.grid_x
        self.static_walls = ((torch.abs(x) > 0.94) | (torch.abs(y) > 0.94)).float().view(1, 1, COMPUTE_RES, COMPUTE_RES)
        
        self.freqs_hz = torch.linspace(1.0, 100.0, 100, device=device).view(1, 100, 1, 1)
        self.w_red   = torch.exp(-((self.freqs_hz - 65.0) ** 2) / 600.0)
        self.w_green = torch.exp(-((self.freqs_hz - 24.0) ** 2) / 144.0)
        self.w_blue  = torch.exp(-((self.freqs_hz - 8.0) ** 2) / 100.0)
        self.wall_color = torch.tensor([50, 15, 60], dtype=torch.uint8, device=device).view(3, 1)

        self.actors = []
        self.damage_numbers = []
        self.combat_time = 0.0
        self.winner = None
        self.synergies = {}
        self.transition_timer = 2.2 

        self.generate_campaign_matchup()
        self.update_synergies()

    def log_event(self, msg):
        if not hasattr(self, 'combat_log'): self.combat_log = []
        if not self.combat_log or self.combat_log[-1] != msg:
            self.combat_log.append(msg)
            if len(self.combat_log) > 8: self.combat_log.pop(0)

    def generate_campaign_matchup(self):
        allies_configs = [
            {"style": "Tank", "weapon": "Shield", "creature": "Angel", "pos": [150, 200], "name": "Gabriel Aegis"},
            {"style": "Tank", "weapon": "Shield", "creature": "Dendro", "pos": [150, 450], "name": "Yggdrasil Oak"},
            {"style": "Fighter", "weapon": "Sword", "creature": "Furry", "pos": [220, 150], "name": "Fenrir Strike"},
            {"style": "Fighter", "weapon": "Sword", "creature": "Human", "pos": [220, 320], "name": "King Arthur"},
            {"style": "Fighter", "weapon": "Bow", "creature": "Human", "pos": [220, 500], "name": "Robin Arrow"},
            {"style": "Fighter", "weapon": "Shuriken", "creature": "Necro", "pos": [200, 580], "name": "Shadow Kunai"},
            {"style": "Mage", "weapon": "Magic", "creature": "Demon", "pos": [100, 300], "name": "Lilith Abyss"},
            {"style": "Healer", "weapon": "Heal", "creature": "Angel", "pos": [80, 400], "name": "Raphael Cure"}
        ]
        
        for cfg in allies_configs:
            color = (0, 180 + random.randint(0, 75), 180 + random.randint(0, 75))
            act = SoftbodyActor(cfg["pos"], 0, color, cfg["name"], cfg["style"], cfg["weapon"], cfg["creature"], self.ally_level, 95)
            self.actors.append(act)

        local_rand = random.Random(self.master_seed + self.current_stage * 1337)
        weapons = ["Sword", "Bow", "Magic", "Heal", "Shield", "Shuriken"]
        creatures = ["Dendro", "Necro", "Demon", "Furry", "Human", "Angel"]
        enemy_styles = ["Fighter", "Fighter", "Mage", "Healer", "Tank", "Fighter", "Mage", "Tank"]
        
        enemy_lv = int(5 * (1.08) ** self.current_stage) + self.current_stage * 2
        is_boss_stage = (self.current_stage % 5 == 0)
        enemy_names = ["Hundun Guard", "Lich Thrall", "Astaroth Spawn", "Behemoth Pup", "Plague Drone", "Hanzo Disciple", "Azazel Spark", "Baphomet Disc"]
        fractal_mult = 1.0 + (0.25 if self.current_stage%5==0 else 0) + (0.5 if self.current_stage%10==0 else 0)
        
        for i in range(8):
            e_pos = [600 + local_rand.randint(-40, 120), 100 + i * 85]
            if i == 0 and is_boss_stage:
                color = (180 + local_rand.randint(0, 75), 30, 0)
                act = SoftbodyActor(e_pos, 1, color, "BOSS", "Tank", "Shield", local_rand.choice(creatures), int(enemy_lv * fractal_mult) + 10, 100)
                act.power *= 3
                act.pin_x *= 2.5
                act.pin_y *= 2.5
            else:
                color = (150 + local_rand.randint(0, 50), 80, 40)
                act = SoftbodyActor(e_pos, 1, color, enemy_names[i], enemy_styles[i], local_rand.choice(weapons), local_rand.choice(creatures), enemy_lv, 85)
            self.actors.append(act)

    def update_synergies(self):
        syn = {}
        for act in self.actors:
            if not act.is_dead:
                syn[f"team{act.team}_{act.weapon}"] = syn.get(f"team{act.team}_{act.weapon}", 0) + 1
                syn[f"team{act.team}_{act.creature}"] = syn.get(f"team{act.team}_{act.creature}", 0) + 1
        self.synergies = syn

    def fire_bow(self, source, target_pos):
        s_pos = source.pos.cpu().numpy()
        dir_x, dir_y = target_pos[0] - s_pos[0], target_pos[1] - s_pos[1]
        dist = math.hypot(dir_x, dir_y) + 1e-5
        dir_x, dir_y = float(dir_x / dist), float(dir_y / dist)
        
        inj_x, inj_y = s_pos[0] + dir_x * 55.0, s_pos[1] + dir_y * 55.0
        gx, gy = int((inj_x / ARENA_WIDTH) * COMPUTE_RES), int((inj_y / HEIGHT) * COMPUTE_RES)
        
        success = False
        freq = 60.0 if source.team == 0 else 65.0
        
        if 2 <= gx < COMPUTE_RES - 2 and 2 <= gy < COMPUTE_RES - 2:
            success = True
            for dy in range(-1, 2):
                for dx in range(-1, 2):
                    r_sq = dx*dx + dy*dy
                    weight = math.exp(-r_sq / 1.5)
                    self.density_spectral[0, int(freq), gy+dy, gx+dx] = torch.clamp(
                        self.density_spectral[0, int(freq), gy+dy, gx+dx] + weight * 2.1, 0.0, 2.2
                    )
                    self.u[0, 0, gy+dy, gx+dx] = float(dir_x * 900.0 * weight)
                    self.v[0, 0, gy+dy, gx+dx] = float(dir_y * 900.0 * weight)
                        
        source.current_action = "[SHOOTING]" if success else "[BLOCKED]"
        return success

    def fire_shuriken(self, source, target_pos):
        s_pos = source.pos.cpu().numpy()
        dir_x, dir_y = target_pos[0] - s_pos[0], target_pos[1] - s_pos[1]
        dist = math.hypot(dir_x, dir_y) + 1e-5
        dx, dy = float(dir_x / dist), float(dir_y / dist)
        
        success = False
        angles = [-0.42, 0.0, 0.42]
        freq = 40.0 if source.team == 0 else 45.0
        
        for a in angles:
            rx, ry = dx * math.cos(a) - dy * math.sin(a), dx * math.sin(a) + dy * math.cos(a)
            rx, ry = float(rx), float(ry)
            inj_x, inj_y = s_pos[0] + rx * 55.0, s_pos[1] + ry * 55.0
            gx, gy = int((inj_x / ARENA_WIDTH) * COMPUTE_RES), int((inj_y / HEIGHT) * COMPUTE_RES)
            
            if 2 <= gx < COMPUTE_RES - 2 and 2 <= gy < COMPUTE_RES - 2:
                success = True
                for dy_offset in range(-1, 2):
                    for dx_offset in range(-1, 2):
                        r_sq = dx_offset**2 + dy_offset**2
                        weight = math.exp(-r_sq / 1.5)
                        self.density_spectral[0, int(freq), gy+dy_offset, gx+dx_offset] = torch.clamp(
                            self.density_spectral[0, int(freq), gy+dy_offset, gx+dx_offset] + weight * 1.8, 0.0, 2.0
                        )
                        self.u[0, 0, gy+dy_offset, gx+dx_offset] = float(rx * 880.0 * weight)
                        self.v[0, 0, gy+dy_offset, gx+dx_offset] = float(ry * 880.0 * weight)
                        if r_sq > 0:
                            tx = -float(dy_offset) / math.sqrt(r_sq)
                            ty = float(dx_offset) / math.sqrt(r_sq)
                            self.u[0, 0, gy+dy_offset, gx+dx_offset] += float(tx * 600.0 * weight)
                            self.v[0, 0, gy+dy_offset, gx+dx_offset] += float(ty * 600.0 * weight)
        return success

    def fire_heal_soliton(self, source, target_pos):
        s_pos = source.pos.cpu().numpy()
        dir_x, dir_y = target_pos[0] - s_pos[0], target_pos[1] - s_pos[1]
        dist = math.hypot(dir_x, dir_y) + 1e-5
        dir_x, dir_y = float(dir_x / dist), float(dir_y / dist)
        
        inj_x, inj_y = s_pos[0] + dir_x * 45.0, s_pos[1] + dir_y * 45.0
        gx, gy = int((inj_x / ARENA_WIDTH) * COMPUTE_RES), int((inj_y / HEIGHT) * COMPUTE_RES)
        
        success = False
        if 2 <= gx < COMPUTE_RES - 2 and 2 <= gy < COMPUTE_RES - 2:
            success = True
            pwr = COMBAT_BALANCE_CONFIG["HEAL_SOLITON_POWER"]
            for dy in range(-1, 2):
                for dx in range(-1, 2):
                    r_sq = dx*dx + dy*dy
                    weight = math.exp(-r_sq / 1.5)
                    self.density_spectral[0, 6, gy+dy, gx+dx] = torch.clamp(
                        self.density_spectral[0, 6, gy+dy, gx+dx] + weight * pwr, 0.0, 2.5
                    )
                    self.u[0, 0, gy+dy, gx+dx] = float(dir_x * 700.0 * weight)
                    self.v[0, 0, gy+dy, gx+dx] = float(dir_y * 700.0 * weight)
        return success

    def channel_magic(self, source, target_pos, dt):
        s_pos = source.pos.cpu().numpy()
        dir_x, dir_y = target_pos[0] - s_pos[0], target_pos[1] - s_pos[1]
        dist = math.hypot(dir_x, dir_y) + 1e-5
        dir_x, dir_y = float(dir_x / dist), float(dir_y / dist)
        
        inj_x, inj_y = s_pos[0] + dir_x * 35.0, s_pos[1] + dir_y * 35.0
        pulse = 1.0 + 0.6 * math.sin(self.combat_time * 15.0 + source.pos[0].item())
        
        gx, gy = int((inj_x / ARENA_WIDTH) * COMPUTE_RES), int((inj_y / HEIGHT) * COMPUTE_RES)
        if 2 <= gx < COMPUTE_RES - 2 and 2 <= gy < COMPUTE_RES - 2:
            freq = 80.0 if source.team == 0 else 85.0
            self.density_spectral[0, int(freq), gy-1:gy+2, gx-1:gx+2] += 30.0 * dt * pulse
            self.u[0, 0, gy-1:gy+2, gx-1:gx+2] += dir_x * 800.0 * dt * pulse
            self.v[0, 0, gy-1:gy+2, gx-1:gx+2] += dir_y * 800.0 * dt * pulse

    def channel_sword(self, source, target_pos, dt):
        s_pos = source.pos.cpu().numpy()
        dir_x, dir_y = target_pos[0] - s_pos[0], target_pos[1] - s_pos[1]
        dist = math.hypot(dir_x, dir_y) + 1e-5
        dir_x, dir_y = float(dir_x / dist), float(dir_y / dist)
        
        px, py = -dir_y, dir_x
        freq = 80.0 if source.team == 0 else 85.0
        
        for offset in [-16, -8, 0, 8, 16]:
            sag = -0.4 * abs(offset)
            inj_x = s_pos[0] + dir_x * (30.0 + sag) + px * offset
            inj_y = s_pos[1] + dir_y * (30.0 + sag) + py * offset
            
            gx, gy = int((inj_x / ARENA_WIDTH) * COMPUTE_RES), int((inj_y / HEIGHT) * COMPUTE_RES)
            if 2 <= gx < COMPUTE_RES - 2 and 2 <= gy < COMPUTE_RES - 2:
                self.density_spectral[0, 24, gy-1:gy+2, gx-1:gx+2] += 40.0 * dt
                self.density_spectral[0, int(freq), gy-1:gy+2, gx-1:gx+2] += 30.0 * dt
                self.u[0, 0, gy-1:gy+2, gx-1:gx+2] += dir_x * 1600.0 * dt
                self.v[0, 0, gy-1:gy+2, gx-1:gx+2] += dir_y * 1600.0 * dt

    def channel_shield(self, source, dt):
        s_pos = source.pos.cpu().numpy()
        gx, gy = int((s_pos[0] / ARENA_WIDTH) * COMPUTE_RES), int((s_pos[1] / HEIGHT) * COMPUTE_RES)
        if 3 <= gx < COMPUTE_RES - 3 and 3 <= gy < COMPUTE_RES - 3:
            pwr = COMBAT_BALANCE_CONFIG["SHIELD_CHANNEL_POWER"]
            for dy in range(-3, 4):
                for dx in range(-3, 4):
                    if dx*dx + dy*dy <= 9:
                        weight = 1.0 - (dx*dx + dy*dy)/10.0
                        self.density_spectral[0, 10, gy+dy, gx+dx] += weight * pwr * dt

    def channel_heal(self, source, dt):
        s_pos = source.pos.cpu().numpy()
        gx, gy = int((s_pos[0] / ARENA_WIDTH) * COMPUTE_RES), int((s_pos[1] / HEIGHT) * COMPUTE_RES)
        if 3 <= gx < COMPUTE_RES - 3 and 3 <= gy < COMPUTE_RES - 3:
            pwr = COMBAT_BALANCE_CONFIG["HEAL_MIST_CHANNEL_POWER"]
            for dy in range(-3, 4):
                for dx in range(-3, 4):
                    if dx*dx + dy*dy <= 9:
                        weight = 1.0 - (dx*dx + dy*dy)/10.0
                        self.density_spectral[0, 6, gy+dy, gx+dx] += weight * pwr * dt

    def cast_ultimate(self, actor):
        enemies = [a for a in self.actors if a.team != actor.team and not a.is_dead]
        if not enemies: return
        target = min(enemies, key=lambda e: torch.norm(e.pos - actor.pos).item())
        self.log_event(f"{actor.name[:12].upper()} CASTS ULT!")
        t_pos = target.pos.cpu().numpy()
        
        if actor.weapon == "Bow":
            for _ in range(5): self.fire_bow(actor, t_pos + np.random.randn(2)*20)
        elif actor.weapon == "Shuriken":
            for _ in range(3): self.fire_shuriken(actor, t_pos + np.random.randn(2)*15)
        elif actor.weapon == "Sword":
            self.channel_sword(actor, t_pos, 1.0)
            self.channel_sword(actor, t_pos, 1.0)
        elif actor.weapon == "Magic":
            self.channel_magic(actor, t_pos, 1.0)
        elif actor.weapon == "Shield":
            self.channel_shield(actor, 2.0) 
        else: # Healer
            self.channel_heal(actor, 2.0) 

    def step(self, dt):
        self.alch_resources += 5.0 * (1.05) ** self.current_stage * dt
        if self.alch_resources >= 100.0 * (1.06) ** self.ally_level:
            self.alch_resources -= 100.0 * (1.06) ** self.ally_level
            self.ally_level += 1
            for act in self.actors:
                if act.team == 0: act.level = self.ally_level; act.power = act.calculate_power()

        if self.winner is not None:
            self.transition_timer -= dt
            return

        self.combat_time += dt
        self.update_synergies()
        self.resolve_solitonic_collisions(dt)

        # --- 90-SECOND MATCH TIMEOUT DECISION (ATTACKER FAILURE RULE) ---
        match_limit = COMBAT_BALANCE_CONFIG["MATCH_DURATION_LIMIT"]
        if self.combat_time >= match_limit and self.winner is None:
            # If Attacker fails to destroy Defender in 90s, Defender wins!
            if COMBAT_BALANCE_CONFIG.get("ATTACKER_TIMEOUT_PENALTY", True):
                self.winner = "Team 1 (Horde) [TIMEOUT DEFEAT]"
            else:
                t0_hp = sum(a.integrity for a in self.actors if a.team == 0 and not a.is_dead)
                t1_hp = sum(a.integrity for a in self.actors if a.team == 1 and not a.is_dead)
                self.winner = "Team 0 (Alliance)" if t0_hp > t1_hp else "Team 1 (Horde)"

        if not hasattr(self, 'bus'):
            self.bus = TacticalBus()

        # ====================================================================
        # NON-LINEAR SCHRÖDINGER PHYSICS (BALANCED NON-LINEAR THRESHOLDS)
        # ====================================================================
        lap_spec = self.solver.compute_laplacian(self.density_spectral)
        
        shuriken_spec = self.density_spectral[:, 37:50]
        bow_spec      = self.density_spectral[:, 50:70]
        magic_spec    = self.density_spectral[:, 70:90]
        
        self.density_spectral[:, 37:50] += 2.0 * shuriken_spec * (shuriken_spec - 0.7) * (1.8 - shuriken_spec) * dt
        self.density_spectral[:, 50:70] += 2.5 * bow_spec * (bow_spec - 0.9) * (2.2 - bow_spec) * dt
        self.density_spectral[:, 70:90] += 2.0 * magic_spec * (magic_spec - 0.8) * (1.8 - magic_spec) * dt
        
        diff_coeff = (0.04 / torch.sqrt(self.freqs_hz))
        diff_coeff[:, 37:70] *= 0.1
        self.density_spectral = torch.clamp(self.density_spectral + lap_spec * diff_coeff * dt, 0.0, 3.5)

        psi_prev, psi_next = torch.roll(self.density_spectral, 1, 1), torch.roll(self.density_spectral, -1, 1)
        self.density_spectral = torch.clamp(self.density_spectral + 0.5 * self.density_spectral * (psi_prev - psi_next) * dt, 0.0, 3.5)

        self.density_spectral[:, 70:90] *= torch.clamp(torch.tensor(1.0 - 1.2 * dt, device=device), 0.0, 1.0)
        self.density_spectral[:, 50:70] *= torch.clamp(torch.tensor(1.0 - 0.8 * dt, device=device), 0.0, 1.0)
        self.density_spectral[:, 37:50] *= torch.clamp(torch.tensor(1.0 - 1.2 * dt, device=device), 0.0, 1.0)
        self.density_spectral[:, 18:37] *= torch.clamp(torch.tensor(1.0 - 4.5 * dt, device=device), 0.0, 1.0)
        self.density_spectral[:, 4:9] *= torch.clamp(torch.tensor(1.0 - 2.5 * dt, device=device), 0.0, 1.0)
        self.density_spectral[:, 9:13] *= torch.clamp(torch.tensor(1.0 - 2.5 * dt, device=device), 0.0, 1.0)

        theta_sum = torch.sum(self.density_spectral[:, 4:9], dim=1, keepdim=True)
        beta_sum = torch.sum(self.density_spectral[:, 18:37], dim=1, keepdim=True)
        
        grad_t_x, grad_t_y = self.solver.compute_gradient(theta_sum)
        grad_b_x, grad_b_y = self.solver.compute_gradient(beta_sum)
        
        clash_dot = grad_t_x * grad_b_x + grad_t_y * grad_b_y
        interface = torch.clamp(torch.relu(-clash_dot) * 2.0, 0.0, 2.0)
        
        kinetic_clash = torch.clamp(torch.relu(-interface * (self.u * grad_t_x + self.v * grad_t_y)), 0.0, 50.0)
        self.density_spectral[:, 70:85, :, :] += kinetic_clash * 1.5 * dt
        self.u += grad_t_x * kinetic_clash * 5.0 * dt
        self.v += grad_t_y * kinetic_clash * 5.0 * dt

        shuriken_band = torch.sum(self.density_spectral[:, 37:50], dim=1, keepdim=True) 
        bow_band      = torch.sum(self.density_spectral[:, 50:70], dim=1, keepdim=True) 
        magic_band    = torch.sum(self.density_spectral[:, 70:90], dim=1, keepdim=True) 
        
        local_friction = torch.clamp(4.5 - (shuriken_band * 5.0 + bow_band * 10.0 + magic_band * 3.0), 0.0, 4.5)
        self.u *= torch.clamp(1.0 - local_friction * dt, 0.0, 1.0)
        self.v *= torch.clamp(1.0 - local_friction * dt, 0.0, 1.0)
        
        u_proj, v_proj = self.solver.project(self.u, self.v, self.static_walls)
        soliton_presence = torch.clamp(shuriken_band + bow_band, 0.0, 1.0)
        self.u = u_proj * (1.0 - soliton_presence) + self.u * soliton_presence
        self.v = v_proj * (1.0 - soliton_presence) + self.v * soliton_presence
        
        self.u = torch.clamp(self.u, -1200.0, 1200.0)
        self.v = torch.clamp(self.v, -1200.0, 1200.0)
        
        speed = torch.sqrt(self.u**2 + self.v**2) + 1e-5
        self.u += (self.u/speed) * (shuriken_band * 1000.0 + bow_band * 1600.0 + magic_band * 450.0) * dt
        self.v += (self.v/speed) * (shuriken_band * 1000.0 + bow_band * 1600.0 + magic_band * 450.0) * dt
        
        beta_band = torch.sum(self.density_spectral[:, 18:37], dim=1, keepdim=True)
        beta_mask = (beta_band > 0.2).float()
        gx_b, gy_b = self.solver.compute_gradient(beta_band)
        self.u += -gy_b * 200.0 * beta_mask * (1.0 - soliton_presence) * dt 
        self.v += gx_b * 200.0 * beta_mask * (1.0 - soliton_presence) * dt

        block_mask = (self.static_walls > 0.4).float()
        self.u *= (1.0 - block_mask)
        self.v *= (1.0 - block_mask)
        self.density_spectral[:, 37:100] *= (1.0 - block_mask)

        # --- TARGET ABSORPTION & HEALING (CLEAN CONSTANT RATES) ---
        t0_pwr = sum(a.power for a in self.actors if a.team == 0 and not a.is_dead)
        t1_pwr = sum(a.power for a in self.actors if a.team == 1 and not a.is_dead)
        dmg_modifier = math.sqrt(t0_pwr / (t1_pwr + 1e-5))

        for act in self.actors:
            if act.is_dead: continue
            
            c_cfg = CREATURE_CONFIGS.get(act.creature, {"hp_mult": 1.0})
            
            for i in range(16):
                nx, ny = act.pin_pos[i, 0].item(), act.pin_pos[i, 1].item()
                gx, gy = int((nx / ARENA_WIDTH) * COMPUTE_RES), int((ny / HEIGHT) * COMPUTE_RES)
                
                if 0 <= gx < COMPUTE_RES and 0 <= gy < COMPUTE_RES:
                    theta_val = self.density_spectral[0, 4:9, gy, gx].sum().item()   # Heal (6Hz)
                    alpha_val = self.density_spectral[0, 9:13, gy, gx].sum().item()  # Shield (10Hz)
                    
                    if act.team == 0:
                        gamma_val = self.density_spectral[0, [45, 65, 85], gy, gx].sum().item()
                    else:
                        gamma_val = self.density_spectral[0, [40, 60, 80], gy, gx].sum().item()
                    
                    # Shield Barrier Physics
                    if alpha_val > 0.30:
                        pen_ratio = COMBAT_BALANCE_CONFIG["SHIELD_PENETRATION_RATIO"]
                        self.density_spectral[0, 60:100, gy, gx] *= pen_ratio 
                        self.u[0, 0, gy, gx] *= 0.25 
                        self.v[0, 0, gy, gx] *= 0.25 
                        gamma_val *= pen_ratio
                    
                    if gamma_val > 0.60: 
                        pwr_scale = max(0.15, min(4.5, dmg_modifier if act.team == 1 else (1.0 / (dmg_modifier + 1e-5))))
                        dmg_rate = (gamma_val * COMBAT_BALANCE_CONFIG["DAMAGE_SCALE_BASE"] * pwr_scale) / c_cfg["hp_mult"]
                        
                        act.node_phases[i] += 4.5 * dt
                        act.edge_intact[i] = False  
                        act.integrity = max(0.0, act.integrity - dmg_rate * dt)
                        act.ult_charge = min(1.0, act.ult_charge + dmg_rate * dt * 0.5)
                        
                        if random.random() < 0.15:
                            self.damage_numbers.append({"pos": [nx, ny], "text": f"-{int(dmg_rate * 100)}", "life": 1.0, "color": (255, 100, 100) if act.team == 0 else (0, 255, 255)})

                        self.density_spectral[0, 37:100, gy, gx] *= 0.1
                        self.u[0, 0, gy, gx] *= 0.1
                        self.v[0, 0, gy, gx] *= 0.1
                        
                    # Standard constant linear healing rate (DPS > HPS means focused damage out-paces healing)
                    if theta_val > 0.25 and act.integrity < 1.0:
                        heal_rate = theta_val * COMBAT_BALANCE_CONFIG["BASE_HEAL_RATE"]
                        act.integrity = min(1.0, act.integrity + heal_rate * dt)
                        act.edge_intact[i] = True  
                        self.density_spectral[0, 4:9, gy, gx] *= torch.clamp(torch.tensor(1.0 - 2.5*dt, device=device), 0.0, 1.0)
            
            if act.integrity <= 0.005: act.is_dead = True

        # ADVECTION & PROJECTION
        self.density_spectral = self.solver.advect(self.density_spectral, self.u, self.v, dt)
        self.u = self.solver.advect(self.u, self.u, self.v, dt)
        self.v = self.solver.advect(self.v, self.u, self.v, dt)

        # ====================================================================
        # PHASE 1: EVENT BROKER PUBLISHING (PUBLISH TACTICAL INTENTS)
        # ====================================================================
        self.bus.clear()
        
        for act in self.actors:
            if act.is_dead: continue
            
            enemies = [e for e in self.actors if e.team != act.team and not e.is_dead]
            if enemies:
                target_enemy = min(enemies, key=lambda e: (e.integrity, torch.norm(e.pos - act.pos).item()))
                dist_e = torch.norm(target_enemy.pos - act.pos).item()
                
                if act.weapon in ["Bow", "Shuriken", "Magic", "Sword"]:
                    t_pos = act.channel_target.pos.cpu().numpy() if (act.channel_duration > 0 and act.channel_target and not act.channel_target.is_dead) else target_enemy.pos.cpu().numpy()
                    self.bus.publish_corridor(act.team, act.name, act.pos.cpu().numpy(), t_pos, act.weapon)
                    
                if dist_e < 220.0 and act.style != "Tank":
                    self.bus.publish_defense_request(
                        act.team, act.name, act.pos.cpu().numpy(), 
                        target_enemy.pos.cpu().numpy(), urgency=(220.0 - dist_e) / 220.0
                    )

        # ====================================================================
        # PHASE 2: SUBSCRIBED TACTICAL AI REACTION
        # ====================================================================
        for act in self.actors:
            if act.is_dead: 
                act.current_action = "[DEAD]"
                continue
            
            enemies = [e for e in self.actors if e.team != act.team and not e.is_dead]
            allies = [a for a in self.actors if a.team == act.team and not a.is_dead and a is not act]
            
            steer_dir = np.array([0.0, 0.0])
            w_cfg = WEAPON_CONFIGS.get(act.weapon, {"cooldown": 1.0})
            
            if enemies:
                target_enemy = min(enemies, key=lambda e: (e.integrity, torch.norm(e.pos - act.pos).item()))
                dist_enemy = torch.norm(target_enemy.pos - act.pos).item()
                dir_enemy = (target_enemy.pos - act.pos).cpu().numpy() / (dist_enemy + 1e-5)
                
                if act.weapon == "Magic":
                    if dist_enemy > 250.0: steer_dir = dir_enemy; act.current_action = "[SEEKING]"
                    elif dist_enemy < 180.0: steer_dir = -dir_enemy; act.current_action = "[KITING]"
                    else: act.current_action = "[AIMING]"
                    
                    if act.channel_duration > 0:
                        act.channel_duration -= dt
                        if act.channel_target and not act.channel_target.is_dead:
                            self.channel_magic(act, act.channel_target.pos.cpu().numpy(), dt)
                            steer_dir = np.array([0.0, 0.0])
                        else: act.channel_duration = 0.0 
                    else:
                        act.cooldown -= dt
                        if act.cooldown <= 0:
                            act.channel_target = target_enemy
                            act.channel_duration = random.uniform(2.0, 3.5)
                            act.cooldown = w_cfg["cooldown"]
                            
                elif act.weapon == "Shield":
                    def_reqs = self.bus.defense_requests[act.team]
                    
                    if def_reqs:
                        top_req = max(def_reqs, key=lambda r: r["urgency"])
                        ally_p = top_req["pos"]
                        threat_p = top_req["threat_source"]
                        
                        ray_vec = threat_p - ally_p
                        ray_dist = math.hypot(ray_vec[0], ray_vec[1]) + 1e-5
                        intercept_pos = ally_p + (ray_vec / ray_dist) * min(70.0, ray_dist * 0.5)
                        
                        avoid_steer = compute_corridor_avoidance(intercept_pos, self.bus.attack_corridors[act.team], clearance=50.0)
                        intercept_pos += avoid_steer * 20.0
                        
                        dir_target = intercept_pos - act.pos.cpu().numpy()
                        dist_target = math.hypot(dir_target[0], dir_target[1]) + 1e-5
                        steer_dir = dir_target / dist_target
                        act.current_action = f"[GUARD {top_req['requester'][:4].upper()}]"
                    else:
                        intercept_pos = target_enemy.pos.cpu().numpy()
                        dir_intercept = intercept_pos - act.pos.cpu().numpy()
                        dist_intercept = math.hypot(dir_intercept[0], dir_intercept[1]) + 1e-5
                        
                        if dist_intercept > 40.0: steer_dir = dir_intercept / dist_intercept; act.current_action = "[INTERCEPTING]"
                        else: steer_dir = (dir_intercept / dist_intercept) * 0.2; act.current_action = "[BLOCKING]"
                        
                    avoid_steer = compute_corridor_avoidance(act.pos, self.bus.attack_corridors[act.team], clearance=55.0)
                    steer_dir += avoid_steer
                    
                    if act.channel_duration > 0:
                        act.channel_duration -= dt
                        self.channel_shield(act, dt)
                    else:
                        act.cooldown -= dt
                        if act.cooldown <= 0:
                            act.channel_duration = random.uniform(1.5, 3.0)
                            act.cooldown = w_cfg["cooldown"]
                            
                elif act.weapon == "Heal":
                    team_members = [a for a in self.actors if a.team == act.team and not a.is_dead and a.integrity < 0.98]
                    
                    if team_members:
                        weakest = min(team_members, key=lambda a: a.integrity)
                        t_pos = weakest.pos.cpu().numpy()
                        dir_target = t_pos - act.pos.cpu().numpy()
                        dist_target = math.hypot(dir_target[0], dir_target[1]) + 1e-5
                        
                        if weakest is act:
                            steer_dir = np.array([0.0, 0.0])
                            act.current_action = "[HEALING SELF]"
                            self.channel_heal(act, dt)
                        else:
                            if dist_target > 40.0:
                                steer_dir = dir_target / dist_target
                                act.current_action = f"[HEALING {weakest.name[:4].upper()}]"
                            else:
                                steer_dir = np.array([0.0, 0.0])
                                act.current_action = f"[MISTING {weakest.name[:4].upper()}]"
                                self.channel_heal(act, dt)
                                
                            if dist_target > 90.0 and act.cooldown <= 0.0:
                                if self.fire_heal_soliton(act, t_pos):
                                    act.current_action = f"[PULSE {weakest.name[:4].upper()}]"
                                    act.cooldown = w_cfg["cooldown"]
                    else:
                        if dist_enemy < 200.0: steer_dir = -dir_enemy; act.current_action = "[KITING]"
                        else: steer_dir = np.array([0.0, 0.0]); act.current_action = "[POSITIONING]"
                            
                    avoid_steer = compute_corridor_avoidance(act.pos, self.bus.attack_corridors[act.team], clearance=60.0)
                    steer_dir += avoid_steer

                elif act.weapon == "Sword":
                    steer_dir = dir_enemy; act.current_action = "[RUSHING]"
                    if act.channel_duration > 0:
                        act.channel_duration -= dt
                        if act.channel_target and not act.channel_target.is_dead:
                            self.channel_sword(act, act.channel_target.pos.cpu().numpy(), dt)
                            steer_dir = dir_enemy * 0.5 
                        else: act.channel_duration = 0.0
                    else:
                        act.cooldown -= dt
                        if act.cooldown <= 0 and dist_enemy < 180.0:
                            act.channel_target = target_enemy
                            act.channel_duration = random.uniform(0.5, 1.0)
                            act.cooldown = w_cfg["cooldown"]
                            
                elif act.weapon == "Bow":
                    tangent_vec = np.array([-dir_enemy[1], dir_enemy[0]])
                    if dist_enemy > 320.0: steer_dir = dir_enemy * 0.7 + tangent_vec * 0.3; act.current_action = "[SEEKING]"
                    elif dist_enemy < 220.0: steer_dir = -dir_enemy * 0.7 + tangent_vec * 0.3; act.current_action = "[KITING]"
                    else: steer_dir = tangent_vec * 1.0; act.current_action = "[STRAFING]"
                    
                    act.cooldown -= dt
                    if act.cooldown <= 0:
                        success = self.fire_bow(act, target_enemy.pos.cpu().numpy())
                        act.cooldown = w_cfg["cooldown"] if success else 0.1
                        
                elif act.weapon == "Shuriken":
                    tangent_vec = np.array([-dir_enemy[1], dir_enemy[0]])
                    if dist_enemy > 200.0: steer_dir = dir_enemy * 0.9 + tangent_vec * 0.1; act.current_action = "[SEEKING]"
                    elif dist_enemy < 120.0: steer_dir = -dir_enemy * 1.0; act.current_action = "[KITING]"
                    else: steer_dir = tangent_vec * 1.0; act.current_action = "[STRAFING]"
                    
                    act.cooldown -= dt
                    if act.cooldown <= 0:
                        success = self.fire_shuriken(act, target_enemy.pos.cpu().numpy())
                        if success:
                            act.pin_pos[:, 0] -= dir_enemy[0] * 40.0
                            act.pin_pos[:, 1] -= dir_enemy[1] * 40.0
                            act.current_action = "[BACKDODGE]"
                            act.cooldown = w_cfg["cooldown"]
                        else:
                            act.cooldown = 0.1

            if act.integrity < 0.75 and act.weapon not in ["Heal", "Shield"]:
                friendly_healers = [h for h in allies if h.weapon == "Heal"]
                if friendly_healers:
                    closest_h = min(friendly_healers, key=lambda h: torch.norm(h.pos - act.pos).item())
                    h_dist = torch.norm(closest_h.pos - act.pos).item()
                    if 60.0 < h_dist < 280.0:
                        dir_h = (closest_h.pos - act.pos).cpu().numpy() / (h_dist + 1e-5)
                        steer_dir = steer_dir * 0.4 + dir_h * 0.6
            
            steer_len = math.hypot(steer_dir[0], steer_dir[1])
            if steer_len > 1.0:
                steer_dir = steer_dir / steer_len

            c_cfg = CREATURE_CONFIGS.get(act.creature, {"speed_mult": 1.0})
            base_speed = 100.0 if act.style == "Fighter" else (60.0 if act.style == "Tank" else 45.0)
            move_speed = base_speed * c_cfg["speed_mult"]
            
            act.pin_pos[:, 0] += steer_dir[0] * move_speed * dt
            act.pin_pos[:, 1] += steer_dir[1] * move_speed * dt
            
            act.breather_phase += act.breather_speed * dt
            act.pos.copy_(act.calculate_covariance())
            
            breath_scale = 1.0 + 0.15 * math.sin(act.breather_phase)
            ideal_x = act.pin_x * math.cos(act.angle) * breath_scale + act.pin_y * math.sin(act.angle) * breath_scale
            ideal_y = -act.pin_x * math.sin(act.angle) * breath_scale + act.pin_y * math.cos(act.angle) * breath_scale
            ideal_pos = act.pos.unsqueeze(0) + torch.stack([ideal_x, ideal_y], dim=1)
            
            f_spring = act.update_springs(ideal_pos)
            f_restore = (ideal_pos - act.pin_pos) * (18.0 + act.integrity * 25.0)
            
            node_uv = torch.clamp((act.pin_pos / torch.tensor([ARENA_WIDTH, HEIGHT], device=device)) * 2.0 - 1.0, -1.0, 1.0).view(1, 1, 16, 2)
            fluid_vel = F.grid_sample(torch.stack([self.u, self.v], dim=1).view(1,2,COMPUTE_RES,COMPUTE_RES), node_uv, align_corners=True).squeeze().t() * 75.0
            
            mask = act.edge_intact
            act.pin_pos[mask] += (fluid_vel[mask] + f_restore[mask] + f_spring[mask]) * dt
            
            act.pin_pos[:, 0] = torch.clamp(act.pin_pos[:, 0], 40.0, ARENA_WIDTH - 40.0)
            act.pin_pos[:, 1] = torch.clamp(act.pin_pos[:, 1], 40.0, HEIGHT - 40.0)
            act.pin_pos = apply_cohesion_constraint(act.pin_pos, ideal_pos, 1.25, 0.5)

        if not any(a.team == 0 and not a.is_dead for a in self.actors) and not any(a.team == 1 and not a.is_dead for a in self.actors): 
            self.winner = "Draw"
        elif not any(a.team == 0 and not a.is_dead for a in self.actors): 
            self.winner = "Team 1 (Horde)"
        elif not any(a.team == 1 and not a.is_dead for a in self.actors): 
            self.winner = "Team 0 (Alliance)"

        self.damage_numbers = [ft for ft in self.damage_numbers if (ft.update({'life': ft['life'] - dt, 'pos': [ft['pos'][0], ft['pos'][1] - 35.0*dt]}) or ft['life'] > 0)]

    def resolve_solitonic_collisions(self, dt):
        for i, act_a in enumerate(self.actors):
            if act_a.is_dead: continue
            for j, act_b in enumerate(self.actors):
                if j <= i or act_b.is_dead: continue
                diff = act_a.pos - act_b.pos
                dist = torch.norm(diff).item() + 1e-5
                min_sep = 65.0 if (act_a.name in ["MINI-BOSS", "BOSS", "SUPERBOSS"] or act_b.name in ["MINI-BOSS", "BOSS", "SUPERBOSS"]) else 42.0
                if dist < min_sep:
                    overlap = min_sep - dist
                    act_a.node_phases += 0.8 * overlap * dt
                    act_b.node_phases -= 0.8 * overlap * dt
                    push = (diff / dist) * overlap * 0.52
                    act_a.pin_pos += push
                    act_b.pin_pos -= push

def main():
    pygame.init()
    pygame.font.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption("EXOCORTEX SQUAD ARENA: COMBAT ARSENAL UPDATE")
    clock = pygame.time.Clock()
    
    font_large = pygame.font.SysFont("Consolas", 16, bold=True)
    font_med = pygame.font.SysFont("Consolas", 13, bold=True)
    font_small = pygame.font.SysFont("Consolas", 11)
    
    current_stage, ally_level, alch_resources = 1, 20, 0.0
    arena = BossFightArena(master_seed=TOURNAMENT_SEED, current_stage=current_stage, ally_level=ally_level, alch_resources=alch_resources)
    
    running = True
    last_time = time.time()
    
    while running:
        dt = min(0.032, time.time() - last_time)
        last_time = time.time()
        
        for event in pygame.event.get():
            if event.type == pygame.QUIT or (event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE): running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_r: arena = BossFightArena(master_seed=TOURNAMENT_SEED, current_stage=current_stage, ally_level=ally_level, alch_resources=alch_resources)

        arena.step(dt)
        ally_level, alch_resources = arena.ally_level, arena.alch_resources

        if arena.winner is not None and arena.transition_timer <= 0.0:
            if "Alliance" in arena.winner: current_stage += 1; alch_resources += 500.0 * (1.08) ** current_stage
            arena = BossFightArena(master_seed=TOURNAMENT_SEED, current_stage=current_stage, ally_level=ally_level, alch_resources=alch_resources)

        R = torch.clamp(torch.sum(arena.density_spectral * arena.w_red, dim=1) * 255.0, 0.0, 255.0)
        G = torch.clamp(torch.sum(arena.density_spectral * arena.w_green, dim=1) * 255.0, 0.0, 255.0)
        B = torch.clamp(torch.sum(arena.density_spectral * arena.w_blue, dim=1) * 255.0, 0.0, 255.0)
        
        rgb_tensor = torch.stack([R[0], G[0], B[0]], dim=0).to(torch.uint8)
        rgb_tensor[:, arena.static_walls[0, 0] > 0.5] = arena.wall_color
        
        surf_large = pygame.transform.scale(pygame.surfarray.make_surface(np.transpose(rgb_tensor.permute(1, 2, 0).cpu().numpy(), (1, 0, 2))), (ARENA_WIDTH, HEIGHT))
        screen.blit(surf_large, (0, 0))

        u_np, v_np = arena.u[0, 0].cpu().numpy(), arena.v[0, 0].cpu().numpy()
        for i in range(4, COMPUTE_RES - 4, 8):
            for j in range(4, COMPUTE_RES - 4, 8):
                if (speed := math.hypot(u_np[i, j], v_np[i, j])) > 10.0:
                    pygame.draw.line(screen, (0, int(130 + min(125, speed * 2.0)), 255), 
                                     (int((j / COMPUTE_RES) * ARENA_WIDTH), int((i / COMPUTE_RES) * HEIGHT)), 
                                     (int((j / COMPUTE_RES) * ARENA_WIDTH + (u_np[i, j] / speed) * min(15.0, speed * 0.15)), int((i / COMPUTE_RES) * HEIGHT + (v_np[i, j] / speed) * min(15.0, speed * 0.15))), 1)

        for act in arena.actors:
            if act.is_dead: continue
            nodes = act.pin_pos.cpu().numpy()
            
            for i in range(16):
                if act.edge_intact[i]:
                    pygame.draw.line(screen, act.color, (int(nodes[i, 0]), int(nodes[i, 1])), (int(nodes[(i + 1) % 16, 0]), int(nodes[(i + 1) % 16, 1])), 3)
                pygame.draw.circle(screen, act.color if act.edge_intact[i] else (255, 50, 50), (int(nodes[i, 0]), int(nodes[i, 1])), 3)
                
            bx, by = int(act.pos[0].item() - 20), int(act.pos[1].item() - 35)
            pygame.draw.rect(screen, (40, 40, 50), (bx, by, 40, 4))
            pygame.draw.rect(screen, (0, 255, 150) if act.team == 0 else (255, 100, 100), (bx, by, int(40 * act.integrity), 4))
            
            name_surf = font_small.render(f"{act.name[:8]}", True, (255, 255, 255))
            screen.blit(name_surf, (bx + 20 - name_surf.get_width()//2, by - 12))

        for ft in arena.damage_numbers:
            ts = font_large.render(ft['text'], True, ft['color'])
            ts.set_alpha(int(max(0, min(1.0, ft['life'])) * 255))
            screen.blit(ts, (int(ft['pos'][0] - ts.get_width()//2), int(ft['pos'][1])))

        sidebar_x = ARENA_WIDTH
        pygame.draw.rect(screen, (15, 12, 22), pygame.Rect(sidebar_x, 0, WIDTH - ARENA_WIDTH, HEIGHT))
        pygame.draw.line(screen, (0, 255, 200), (sidebar_x, 0), (sidebar_x, HEIGHT), 2)

        t0_actors = [a for a in arena.actors if a.team == 0]
        t1_actors = [a for a in arena.actors if a.team == 1]
        
        t0_hp = sum(a.integrity for a in t0_actors if not a.is_dead) / 8.0
        t1_hp = sum(a.integrity for a in t1_actors if not a.is_dead) / 8.0

        screen.blit(font_large.render(f"ALLIANCE POWER: {sum(a.power for a in t0_actors)}", True, (0, 255, 200)), (sidebar_x + 15, 12))
        screen.blit(font_large.render(f"HORDE POWER: {sum(a.power for a in t1_actors)}", True, (255, 100, 100)), (sidebar_x + 15, 32))
        
        rem_time = max(0.0, COMBAT_BALANCE_CONFIG["MATCH_DURATION_LIMIT"] - arena.combat_time)
        screen.blit(font_small.render(f"TIME REMAINING: {rem_time:.1f}s | Lvl: {ally_level}", True, (255, 220, 100)), (sidebar_x + 15, 48))

        # Real-time deterministic squad prediction HUD
        preds = predict_squad_matchup(t0_actors, t1_actors)
        wp_str = f"PREDICTED WIN CHANCE: {preds['win_probability_0']:.1f}%"
        ttk_str = f"TTK (Atk): {preds['ttk_0_to_1']:.1f}s | Def: {preds['ttk_1_to_0']:.1f}s"
        screen.blit(font_small.render(wp_str, True, (0, 255, 150) if preds['win_probability_0'] > 50 else (255, 100, 100)), (sidebar_x + 15, 66))
        screen.blit(font_small.render(ttk_str, True, (180, 180, 200)), (sidebar_x + 15, 82))

        pygame.draw.rect(screen, (0, 255, 200), (sidebar_x + 15, 108, int(170 * t0_hp), 8))
        pygame.draw.rect(screen, (255, 100, 100), (sidebar_x + 215, 108, int(170 * t1_hp), 8))

        card_y = 124
        for i in range(8):
            for t_idx, act in enumerate([a for a in arena.actors if a.team == 0][:8] + [a for a in arena.actors if a.team == 1][:8]):
                if t_idx % 8 != i: continue
                cx = sidebar_x + 15 if act.team == 0 else sidebar_x + 210
                pygame.draw.rect(screen, (10, 40, 40) if act.team==0 and not act.is_dead else ((50, 25, 20) if not act.is_dead else (30,30,35)), pygame.Rect(cx, card_y, 175, 52))
                
                status_color = (0, 255, 200) if act.team == 0 else (255, 100, 100)
                if act.channel_duration > 0: status_color = (255, 200, 255) 
                
                screen.blit(font_med.render(f"{act.name[:13]}", True, (255, 255, 255) if not act.is_dead else (120, 120, 120)), (cx + 7, card_y + 4))
                screen.blit(font_small.render(f"Lv.{act.level} {act.weapon}", True, status_color if not act.is_dead else (100, 100, 100)), (cx + 7, card_y + 20))
                
                action_color = (255, 255, 100) if "BLOCKED" in act.current_action else ((100, 255, 100) if "SHOOTING" in act.current_action or "STRIKE" in act.current_action or "CHANNELING" in act.current_action or "HEALING" in act.current_action or "GUARDING" in act.current_action or "STRAFING" in act.current_action or "BACKDODGE" in act.current_action or "PULSE" in act.current_action or "HEAL SELF" in act.current_action else (150, 150, 150))
                screen.blit(font_small.render(act.current_action, True, action_color if not act.is_dead else (100, 100, 100)), (cx + 7, card_y + 35))
                
                if not act.is_dead:
                    pygame.draw.rect(screen, (255, 220, 0), (cx + 100, card_y + 42, int(65 * act.ult_charge), 4))
            card_y += 56

        if arena.winner is not None:
            overlay = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
            overlay.fill((0, 0, 0, 180))
            screen.blit(overlay, (0, 0))
            res_text = pygame.font.SysFont("Consolas", 38, bold=True).render(f"MATCH ENDED: {arena.winner}", True, (0, 255, 180) if 'Alliance' in arena.winner else (255, 80, 80))
            screen.blit(res_text, (WIDTH // 2 - res_text.get_width()//2, HEIGHT // 2 - 40))

        pygame.display.flip()
        clock.tick(60)

if __name__ == "__main__":
    main()
